services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: "file:./dev.db"
      NODE_ENV: development
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backend/src:/app/src
      - ./backend/prisma:/app/prisma
      - ./deployments:/app/deployments
    networks:
      - brimble

  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - brimble
    depends_on:
      - backend

volumes:
  caddy_data:
  caddy_config:

networks:
  brimble:
    driver: bridge
